

morph = {
'adjectif,accusatif,féminin,pluriel':'1',
'adjectif,accusatif,féminin,singulier':'2',
'adjectif,accusatif,masculin,pluriel':'3',
'adjectif,accusatif,masculin,singulier':'4',
'adjectif,accusatif,neutre,pluriel':'5',
'adjectif,accusatif,neutre,singulier':'6',
'adjectif,accusatif,neutre,singulier,comparatif':'7',
'adjectif,datif,féminin,pluriel':'8',
'adjectif,datif,féminin,singulier':'9',
'adjectif,datif,masculin,pluriel':'10',
'adjectif,datif,masculin,singulier':'11',
'adjectif,datif,neutre,pluriel':'12',
'adjectif,datif,neutre,singulier':'13',
'adjectif,génitif,féminin,pluriel':'14',
'adjectif,génitif,féminin,singulier':'15',
'adjectif,génitif,masculin,pluriel':'16',
'adjectif,génitif,masculin,singulier':'17',
'adjectif,génitif,neutre,pluriel':'18',
'adjectif,génitif,neutre,singulier':'19',
'adjectif,nominatif,féminin,pluriel':'20',
'adjectif,nominatif,féminin,singulier':'21',
'adjectif,nominatif,masculin,pluriel':'22',
'adjectif,nominatif,masculin,singulier':'23',
'adjectif,nominatif,neutre,pluriel':'24',
'adjectif,nominatif,neutre,singulier':'25',
'adjectif,vocatif,féminin,singulier':'26',
'adjectif,vocatif,masculin,pluriel':'27',
'adjectif,vocatif,masculin,singulier':'28',
'adjectif,vocatif,neutre,singulier':'29',
'adjectif-prédicatif,accusatif,féminin,pluriel':'30',
'adjectif-prédicatif,accusatif,féminin,singulier':'31',
'adjectif-prédicatif,accusatif,masculin,pluriel':'32',
'adjectif-prédicatif,accusatif,masculin,singulier':'33',
'adjectif-prédicatif,accusatif,neutre,pluriel':'34',
'adjectif-prédicatif,accusatif,neutre,singulier':'35',
'adjectif-prédicatif,datif,féminin,pluriel':'36',
'adjectif-prédicatif,datif,féminin,singulier':'37',
'adjectif-prédicatif,datif,masculin,pluriel':'38',
'adjectif-prédicatif,datif,neutre,singulier':'39',
'adjectif-prédicatif,génitif,féminin,pluriel':'40',
'adjectif-prédicatif,génitif,féminin,singulier':'41',
'adjectif-prédicatif,génitif,masculin,pluriel':'42',
'adjectif-prédicatif,génitif,masculin,singulier':'43',
'adjectif-prédicatif,génitif,neutre,pluriel':'44',
'adjectif-prédicatif,nominatif,féminin,pluriel':'45',
'adjectif-prédicatif,nominatif,féminin,singulier':'46',
'adjectif-prédicatif,nominatif,masculin,pluriel':'47',
'adjectif-prédicatif,nominatif,masculin,singulier':'48',
'adjectif-prédicatif,nominatif,neutre,pluriel':'49',
'adjectif-prédicatif,nominatif,neutre,singulier':'50',
'adjectif-substantif,accusatif,féminin,pluriel':'51',
'adjectif-substantif,accusatif,féminin,singulier':'52',
'adjectif-substantif,accusatif,masculin,pluriel':'53',
'adjectif-substantif,accusatif,masculin,singulier':'54',
'adjectif-substantif,accusatif,neutre,pluriel':'55',
'adjectif-substantif,accusatif,neutre,singulier':'56',
'adjectif-substantif,datif,féminin,pluriel':'57',
'adjectif-substantif,datif,féminin,singulier':'58',
'adjectif-substantif,datif,masculin,pluriel':'59',
'adjectif-substantif,datif,masculin,singulier':'60',
'adjectif-substantif,datif,neutre,pluriel':'61',
'adjectif-substantif,datif,neutre,singulier':'62',
'adjectif-substantif,génitif,féminin,pluriel':'63',
'adjectif-substantif,génitif,féminin,singulier':'64',
'adjectif-substantif,génitif,masculin,pluriel':'65',
'adjectif-substantif,génitif,masculin,singulier':'66',
'adjectif-substantif,génitif,neutre,pluriel':'67',
'adjectif-substantif,génitif,neutre,singulier':'68',
'adjectif-substantif,nominatif,féminin,pluriel':'69',
'adjectif-substantif,nominatif,féminin,singulier':'70',
'adjectif-substantif,nominatif,masculin,pluriel':'71',
'adjectif-substantif,nominatif,masculin,singulier':'72',
'adjectif-substantif,nominatif,neutre,pluriel':'73',
'adjectif-substantif,nominatif,neutre,singulier':'74',
'adjectif-substantif,vocatif,féminin,singulier':'75',
'adjectif-substantif,vocatif,masculin,pluriel':'76',
'adjectif-substantif,vocatif,masculin,singulier':'77',
'adverbe':'78',
'adverbe,accusatif,masculin,singulier':'79',
'adverbe,accusatif,neutre,pluriel':'80',
'adverbe,accusatif,neutre,singulier':'81',
'adverbe,datif,féminin,singulier':'82',
'conjonction':'83',
'conjonction-de-coordination':'84',
'conjonction-de-subordination':'85',
'déterminant-article,3e,datif,féminin,singulier':'86',
'déterminant-article,accusatif,féminin,pluriel':'87',
'déterminant-article,accusatif,féminin,singulier':'88',
'déterminant-article,accusatif,masculin,pluriel':'89',
'déterminant-article,accusatif,masculin,singulier':'90',
'déterminant-article,accusatif,neutre,pluriel':'91',
'déterminant-article,accusatif,neutre,singulier':'92',
'déterminant-article,datif,féminin,pluriel':'93',
'déterminant-article,datif,féminin,singulier':'94',
'déterminant-article,datif,masculin,pluriel':'95',
'déterminant-article,datif,masculin,singulier':'96',
'déterminant-article,datif,neutre,pluriel':'97',
'déterminant-article,datif,neutre,singulier':'98',
'déterminant-article,génitif,féminin,pluriel':'99',
'déterminant-article,génitif,féminin,singulier':'100',
'déterminant-article,génitif,masculin,pluriel':'101',
'déterminant-article,génitif,masculin,singulier':'102',
'déterminant-article,génitif,neutre,pluriel':'103',
'déterminant-article,génitif,neutre,singulier':'104',
'déterminant-article,nominatif,féminin,pluriel':'105',
'déterminant-article,nominatif,féminin,singulier':'106',
'déterminant-article,nominatif,masculin,pluriel':'107',
'déterminant-article,nominatif,masculin,singulier':'108',
'déterminant-article,nominatif,neutre,pluriel':'109',
'déterminant-article,nominatif,neutre,singulier':'110',
'déterminant-article,vocatif,féminin,pluriel':'111',
'déterminant-article,vocatif,féminin,singulier':'112',
'déterminant-article,vocatif,masculin,pluriel':'113',
'déterminant-article,vocatif,masculin,singulier':'114',
'déterminant-article,vocatif,neutre,pluriel':'115',
'déterminant-article,vocatif,neutre,singulier':'116',
'déterminant-différentiel,accusatif,féminin,pluriel':'117',
'déterminant-différentiel,accusatif,féminin,singulier':'118',
'déterminant-différentiel,accusatif,masculin,pluriel':'119',
'déterminant-différentiel,accusatif,masculin,singulier':'120',
'déterminant-différentiel,accusatif,neutre,pluriel':'121',
'déterminant-différentiel,accusatif,neutre,singulier':'122',
'déterminant-différentiel,datif,féminin,pluriel':'123',
'déterminant-différentiel,datif,féminin,singulier':'124',
'déterminant-différentiel,datif,masculin,pluriel':'125',
'déterminant-différentiel,datif,masculin,singulier':'126',
'déterminant-différentiel,datif,neutre,pluriel':'127',
'déterminant-différentiel,datif,neutre,singulier':'128',
'déterminant-différentiel,génitif,féminin,pluriel':'129',
'déterminant-différentiel,génitif,féminin,singulier':'130',
'déterminant-différentiel,génitif,masculin,pluriel':'131',
'déterminant-différentiel,génitif,masculin,singulier':'132',
'déterminant-différentiel,génitif,neutre,singulier':'133',
'déterminant-différentiel,nominatif,féminin,pluriel':'134',
'déterminant-différentiel,nominatif,féminin,singulier':'135',
'déterminant-différentiel,nominatif,masculin,pluriel':'136',
'déterminant-différentiel,nominatif,masculin,singulier':'137',
'déterminant-différentiel,nominatif,neutre,pluriel':'138',
'déterminant-différentiel,nominatif,neutre,singulier':'139',
'déterminant-démonstratif,accusatif,féminin,pluriel':'140',
'déterminant-démonstratif,accusatif,féminin,singulier':'141',
'déterminant-démonstratif,accusatif,masculin,pluriel':'142',
'déterminant-démonstratif,accusatif,masculin,singulier':'143',
'déterminant-démonstratif,accusatif,neutre,pluriel':'144',
'déterminant-démonstratif,accusatif,neutre,singulier':'145',
'déterminant-démonstratif,datif,féminin,pluriel':'146',
'déterminant-démonstratif,datif,féminin,singulier':'147',
'déterminant-démonstratif,datif,masculin,pluriel':'148',
'déterminant-démonstratif,datif,masculin,singulier':'149',
'déterminant-démonstratif,datif,neutre,pluriel':'150',
'déterminant-démonstratif,datif,neutre,singulier':'151',
'déterminant-démonstratif,génitif,féminin,pluriel':'152',
'déterminant-démonstratif,génitif,féminin,singulier':'153',
'déterminant-démonstratif,génitif,masculin,pluriel':'154',
'déterminant-démonstratif,génitif,masculin,singulier':'155',
'déterminant-démonstratif,génitif,neutre,pluriel':'156',
'déterminant-démonstratif,génitif,neutre,singulier':'157',
'déterminant-démonstratif,nominatif,féminin,pluriel':'158',
'déterminant-démonstratif,nominatif,féminin,singulier':'159',
'déterminant-démonstratif,nominatif,masculin,pluriel':'160',
'déterminant-démonstratif,nominatif,masculin,singulier':'161',
'déterminant-démonstratif,nominatif,neutre,pluriel':'162',
'déterminant-démonstratif,nominatif,neutre,singulier':'163',
'déterminant-interrogatif,accusatif,féminin,pluriel':'164',
'déterminant-interrogatif,accusatif,féminin,singulier':'165',
'déterminant-interrogatif,accusatif,masculin,pluriel':'166',
'déterminant-interrogatif,accusatif,masculin,singulier':'167',
'déterminant-interrogatif,accusatif,neutre,singulier':'168',
'déterminant-interrogatif,datif,féminin,singulier':'169',
'déterminant-interrogatif,datif,masculin,singulier':'170',
'déterminant-interrogatif,datif,neutre,pluriel':'171',
'déterminant-interrogatif,datif,neutre,singulier':'172',
'déterminant-interrogatif,génitif,féminin,pluriel':'173',
'déterminant-interrogatif,génitif,féminin,singulier':'174',
'déterminant-interrogatif,génitif,masculin,singulier':'175',
'déterminant-interrogatif,nominatif,féminin,pluriel':'176',
'déterminant-interrogatif,nominatif,féminin,singulier':'177',
'déterminant-interrogatif,nominatif,masculin,pluriel':'178',
'déterminant-interrogatif,nominatif,masculin,singulier':'179',
'déterminant-interrogatif,nominatif,neutre,singulier':'180',
'déterminant-numéral,accusatif,féminin,pluriel':'181',
'déterminant-numéral,accusatif,féminin,singulier':'182',
'déterminant-numéral,accusatif,masculin,pluriel':'183',
'déterminant-numéral,accusatif,masculin,singulier':'184',
'déterminant-numéral,accusatif,neutre,pluriel':'185',
'déterminant-numéral,accusatif,neutre,singulier':'186',
'déterminant-numéral,datif,féminin,pluriel':'187',
'déterminant-numéral,datif,féminin,singulier':'188',
'déterminant-numéral,datif,masculin,pluriel':'189',
'déterminant-numéral,datif,masculin,singulier':'190',
'déterminant-numéral,datif,neutre,pluriel':'191',
'déterminant-numéral,datif,neutre,singulier':'192',
'déterminant-numéral,génitif,féminin,pluriel':'193',
'déterminant-numéral,génitif,féminin,singulier':'194',
'déterminant-numéral,génitif,masculin,pluriel':'195',
'déterminant-numéral,génitif,masculin,singulier':'196',
'déterminant-numéral,génitif,neutre,pluriel':'197',
'déterminant-numéral,génitif,neutre,singulier':'198',
'déterminant-numéral,nominatif,féminin,pluriel':'199',
'déterminant-numéral,nominatif,féminin,singulier':'200',
'déterminant-numéral,nominatif,masculin,pluriel':'201',
'déterminant-numéral,nominatif,masculin,singulier':'202',
'déterminant-numéral,nominatif,neutre,pluriel':'203',
'déterminant-numéral,nominatif,neutre,singulier':'204',
'déterminant-ordinal,accusatif,féminin,pluriel':'205',
'déterminant-ordinal,accusatif,féminin,singulier':'206',
'déterminant-ordinal,accusatif,masculin,singulier':'207',
'déterminant-ordinal,accusatif,neutre,pluriel':'208',
'déterminant-ordinal,accusatif,neutre,singulier':'209',
'déterminant-ordinal,datif,féminin,pluriel':'210',
'déterminant-ordinal,datif,féminin,singulier':'211',
'déterminant-ordinal,datif,masculin,singulier':'212',
'déterminant-ordinal,génitif,féminin,pluriel':'213',
'déterminant-ordinal,génitif,féminin,singulier':'214',
'déterminant-ordinal,génitif,masculin,singulier':'215',
'déterminant-ordinal,génitif,neutre,singulier':'216',
'déterminant-ordinal,nominatif,féminin,singulier':'217',
'déterminant-ordinal,nominatif,masculin,singulier':'218',
'déterminant-ordinal,nominatif,neutre,singulier':'219',
'déterminant-possessif,1e,accusatif,féminin,pluriel':'220',
'déterminant-possessif,1e,accusatif,féminin,singulier':'221',
'déterminant-possessif,1e,accusatif,masculin,pluriel':'222',
'déterminant-possessif,1e,accusatif,masculin,singulier':'223',
'déterminant-possessif,1e,accusatif,neutre,pluriel':'224',
'déterminant-possessif,1e,accusatif,neutre,singulier':'225',
'déterminant-possessif,1e,datif,féminin,pluriel':'226',
'déterminant-possessif,1e,datif,féminin,singulier':'227',
'déterminant-possessif,1e,datif,masculin,pluriel':'228',
'déterminant-possessif,1e,datif,masculin,singulier':'229',
'déterminant-possessif,1e,datif,neutre,pluriel':'230',
'déterminant-possessif,1e,datif,neutre,singulier':'231',
'déterminant-possessif,1e,génitif,féminin,singulier':'232',
'déterminant-possessif,1e,génitif,neutre,pluriel':'233',
'déterminant-possessif,1e,nominatif,féminin,singulier':'234',
'déterminant-possessif,1e,nominatif,masculin,pluriel':'235',
'déterminant-possessif,1e,nominatif,masculin,singulier':'236',
'déterminant-possessif,1e,nominatif,neutre,pluriel':'237',
'déterminant-possessif,1e,nominatif,neutre,singulier':'238',
'déterminant-possessif,2e,accusatif,féminin,singulier':'239',
'déterminant-possessif,2e,datif,féminin,singulier':'240',
'déterminant-possessif,2e,datif,masculin,singulier':'241',
'déterminant-possessif,2e,datif,neutre,singulier':'242',
'déterminant-possessif,2e,génitif,féminin,singulier':'243',
'déterminant-possessif,2e,nominatif,masculin,pluriel':'244',
'déterminant-possessif,2e,nominatif,masculin,singulier':'245',
'déterminant-possessif,2e,nominatif,neutre,singulier':'246',
'déterminant-possessif,accusatif,féminin,pluriel':'247',
'déterminant-possessif,accusatif,féminin,singulier':'248',
'déterminant-possessif,accusatif,masculin,pluriel':'249',
'déterminant-possessif,accusatif,masculin,singulier':'250',
'déterminant-possessif,accusatif,neutre,pluriel':'251',
'déterminant-possessif,accusatif,neutre,singulier':'252',
'déterminant-possessif,datif,féminin,pluriel':'253',
'déterminant-possessif,datif,féminin,singulier':'254',
'déterminant-possessif,datif,masculin,pluriel':'255',
'déterminant-possessif,datif,masculin,singulier':'256',
'déterminant-possessif,datif,neutre,pluriel':'257',
'déterminant-possessif,datif,neutre,singulier':'258',
'déterminant-possessif,génitif,féminin,pluriel':'259',
'déterminant-possessif,génitif,féminin,singulier':'260',
'déterminant-possessif,génitif,masculin,pluriel':'261',
'déterminant-possessif,génitif,masculin,singulier':'262',
'déterminant-possessif,génitif,neutre,pluriel':'263',
'déterminant-possessif,génitif,neutre,singulier':'264',
'déterminant-possessif,nominatif,féminin,pluriel':'265',
'déterminant-possessif,nominatif,féminin,singulier':'266',
'déterminant-possessif,nominatif,masculin,pluriel':'267',
'déterminant-possessif,nominatif,masculin,singulier':'268',
'déterminant-possessif,nominatif,neutre,pluriel':'269',
'déterminant-possessif,nominatif,neutre,singulier':'270',
'déterminant-quantitatif,accusatif,féminin,pluriel':'271',
'déterminant-quantitatif,accusatif,féminin,singulier':'272',
'déterminant-quantitatif,accusatif,masculin,pluriel':'273',
'déterminant-quantitatif,accusatif,masculin,singulier':'274',
'déterminant-quantitatif,accusatif,neutre,pluriel':'275',
'déterminant-quantitatif,accusatif,neutre,singulier':'276',
'déterminant-quantitatif,datif,féminin,pluriel':'277',
'déterminant-quantitatif,datif,féminin,singulier':'278',
'déterminant-quantitatif,datif,masculin,pluriel':'279',
'déterminant-quantitatif,datif,masculin,singulier':'280',
'déterminant-quantitatif,datif,neutre,pluriel':'281',
'déterminant-quantitatif,datif,neutre,singulier':'282',
'déterminant-quantitatif,génitif,féminin,pluriel':'283',
'déterminant-quantitatif,génitif,féminin,singulier':'284',
'déterminant-quantitatif,génitif,masculin,pluriel':'285',
'déterminant-quantitatif,génitif,masculin,singulier':'286',
'déterminant-quantitatif,génitif,neutre,pluriel':'287',
'déterminant-quantitatif,génitif,neutre,singulier':'288',
'déterminant-quantitatif,nominatif,féminin,pluriel':'289',
'déterminant-quantitatif,nominatif,féminin,singulier':'290',
'déterminant-quantitatif,nominatif,masculin,pluriel':'291',
'déterminant-quantitatif,nominatif,masculin,singulier':'292',
'déterminant-quantitatif,nominatif,neutre,pluriel':'293',
'déterminant-quantitatif,nominatif,neutre,singulier':'294',
'déterminant-quantitatif,vocatif,masculin,pluriel':'295',
'déterminant-quantitatif,vocatif,masculin,singulier':'296',
'déterminant-quantitatif,vocatif,neutre,pluriel':'297',
'déterminant-relatif,accusatif,féminin,singulier':'298',
'déterminant-relatif,accusatif,masculin,pluriel':'299',
'déterminant-relatif,accusatif,masculin,singulier':'300',
'déterminant-relatif,accusatif,neutre,pluriel':'301',
'déterminant-relatif,accusatif,neutre,singulier':'302',
'déterminant-relatif,datif,féminin,singulier':'303',
'déterminant-relatif,datif,neutre,singulier':'304',
'déterminant-relatif,génitif,féminin,singulier':'305',
'déterminant-relatif,nominatif,féminin,pluriel':'306',
'déterminant-relatif,nominatif,masculin,pluriel':'307',
'déterminant-relatif,nominatif,neutre,singulier':'308',
'interjection':'309',
'interjection,impératif,aoriste,actif,2e,pluriel':'310',
'interjection,impératif,aoriste,actif,2e,singulier':'311',
'interjection,impératif,présent,actif,2e,pluriel':'312',
'interjection,impératif,présent,actif,2e,singulier':'313',
'interjection,infinitif,présent,actif':'314',
'nom,accusatif,féminin,pluriel':'315',
'nom,accusatif,féminin,singulier':'316',
'nom,accusatif,masculin,pluriel':'317',
'nom,accusatif,masculin,singulier':'318',
'nom,accusatif,neutre,pluriel':'319',
'nom,accusatif,neutre,singulier':'320',
'nom,datif,féminin,pluriel':'321',
'nom,datif,féminin,singulier':'322',
'nom,datif,masculin,pluriel':'323',
'nom,datif,masculin,singulier':'324',
'nom,datif,neutre,pluriel':'325',
'nom,datif,neutre,singulier':'326',
'nom,génitif,féminin,pluriel':'327',
'nom,génitif,féminin,singulier':'328',
'nom,génitif,masculin,pluriel':'329',
'nom,génitif,masculin,singulier':'330',
'nom,génitif,neutre,pluriel':'331',
'nom,génitif,neutre,singulier':'332',
'nom,nominatif,féminin,pluriel':'333',
'nom,nominatif,féminin,singulier':'334',
'nom,nominatif,masculin,pluriel':'335',
'nom,nominatif,masculin,singulier':'336',
'nom,nominatif,neutre,pluriel':'337',
'nom,nominatif,neutre,singulier':'338',
'nom,vocatif,féminin,pluriel':'339',
'nom,vocatif,féminin,singulier':'340',
'nom,vocatif,masculin,pluriel':'341',
'nom,vocatif,masculin,singulier':'342',
'nom,vocatif,neutre,pluriel':'343',
'nom,vocatif,neutre,singulier':'344',
'particule':'345',
'particule-étrangère':'346',
'pronom-démonstratif,3e,nominatif,masculin,singulier':'347',
'pronom-démonstratif,accusatif,féminin,pluriel':'348',
'pronom-démonstratif,accusatif,féminin,singulier':'349',
'pronom-démonstratif,accusatif,masculin,pluriel':'350',
'pronom-démonstratif,accusatif,masculin,singulier':'351',
'pronom-démonstratif,accusatif,neutre,pluriel':'352',
'pronom-démonstratif,accusatif,neutre,singulier':'353',
'pronom-démonstratif,datif,féminin,pluriel':'354',
'pronom-démonstratif,datif,féminin,singulier':'355',
'pronom-démonstratif,datif,masculin,pluriel':'356',
'pronom-démonstratif,datif,masculin,singulier':'357',
'pronom-démonstratif,datif,neutre,pluriel':'358',
'pronom-démonstratif,datif,neutre,singulier':'359',
'pronom-démonstratif,génitif,féminin,pluriel':'360',
'pronom-démonstratif,génitif,féminin,singulier':'361',
'pronom-démonstratif,génitif,masculin,pluriel':'362',
'pronom-démonstratif,génitif,masculin,singulier':'363',
'pronom-démonstratif,génitif,neutre,pluriel':'364',
'pronom-démonstratif,génitif,neutre,singulier':'365',
'pronom-démonstratif,nominatif,féminin,pluriel':'366',
'pronom-démonstratif,nominatif,féminin,singulier':'367',
'pronom-démonstratif,nominatif,masculin,pluriel':'368',
'pronom-démonstratif,nominatif,masculin,singulier':'369',
'pronom-démonstratif,nominatif,neutre,pluriel':'370',
'pronom-démonstratif,nominatif,neutre,singulier':'371',
'pronom-démonstratif,vocatif,féminin,singulier':'372',
'pronom-démonstratif,vocatif,masculin,pluriel':'373',
'pronom-démonstratif,vocatif,masculin,singulier':'374',
'pronom-indéfini,accusatif,féminin,pluriel':'375',
'pronom-indéfini,accusatif,féminin,singulier':'376',
'pronom-indéfini,accusatif,masculin,pluriel':'377',
'pronom-indéfini,accusatif,masculin,singulier':'378',
'pronom-indéfini,accusatif,neutre,pluriel':'379',
'pronom-indéfini,accusatif,neutre,singulier':'380',
'pronom-indéfini,datif,féminin,singulier':'381',
'pronom-indéfini,datif,masculin,pluriel':'382',
'pronom-indéfini,datif,masculin,singulier':'383',
'pronom-indéfini,datif,neutre,pluriel':'384',
'pronom-indéfini,datif,neutre,singulier':'385',
'pronom-indéfini,génitif,féminin,pluriel':'386',
'pronom-indéfini,génitif,féminin,singulier':'387',
'pronom-indéfini,génitif,masculin,pluriel':'388',
'pronom-indéfini,génitif,masculin,singulier':'389',
'pronom-indéfini,génitif,neutre,pluriel':'390',
'pronom-indéfini,génitif,neutre,singulier':'391',
'pronom-indéfini,nominatif,féminin,pluriel':'392',
'pronom-indéfini,nominatif,féminin,singulier':'393',
'pronom-indéfini,nominatif,masculin,pluriel':'394',
'pronom-indéfini,nominatif,masculin,singulier':'395',
'pronom-indéfini,nominatif,neutre,pluriel':'396',
'pronom-indéfini,nominatif,neutre,singulier':'397',
'pronom-indéfini,vocatif,masculin,pluriel':'398',
'pronom-interrogatif,accusatif,féminin,pluriel':'399',
'pronom-interrogatif,accusatif,féminin,singulier':'400',
'pronom-interrogatif,accusatif,masculin,pluriel':'401',
'pronom-interrogatif,accusatif,masculin,singulier':'402',
'pronom-interrogatif,accusatif,neutre,pluriel':'403',
'pronom-interrogatif,accusatif,neutre,singulier':'404',
'pronom-interrogatif,datif,masculin,pluriel':'405',
'pronom-interrogatif,datif,masculin,singulier':'406',
'pronom-interrogatif,datif,neutre,singulier':'407',
'pronom-interrogatif,génitif,féminin,singulier':'408',
'pronom-interrogatif,génitif,masculin,pluriel':'409',
'pronom-interrogatif,génitif,masculin,singulier':'410',
'pronom-interrogatif,génitif,neutre,pluriel':'411',
'pronom-interrogatif,génitif,neutre,singulier':'412',
'pronom-interrogatif,nominatif,féminin,singulier':'413',
'pronom-interrogatif,nominatif,masculin,pluriel':'414',
'pronom-interrogatif,nominatif,masculin,singulier':'415',
'pronom-interrogatif,nominatif,neutre,pluriel':'416',
'pronom-interrogatif,nominatif,neutre,singulier':'417',
'pronom-interrogatif-indéfini,accusatif,neutre,singulier':'418',
'pronom-personnel,1e,accusatif,neutre,pluriel':'419',
'pronom-personnel,1e,accusatif,neutre,singulier':'420',
'pronom-personnel,1e,accusatif,pluriel':'421',
'pronom-personnel,1e,accusatif,singulier':'422',
'pronom-personnel,1e,datif,neutre,pluriel':'423',
'pronom-personnel,1e,datif,pluriel':'424',
'pronom-personnel,1e,datif,singulier':'425',
'pronom-personnel,1e,génitif,féminin,pluriel':'426',
'pronom-personnel,1e,génitif,masculin,singulier':'427',
'pronom-personnel,1e,génitif,pluriel':'428',
'pronom-personnel,1e,génitif,singulier':'429',
'pronom-personnel,1e,nominatif,féminin,singulier':'430',
'pronom-personnel,1e,nominatif,masculin,pluriel':'431',
'pronom-personnel,1e,nominatif,masculin,singulier':'432',
'pronom-personnel,1e,nominatif,neutre,pluriel':'433',
'pronom-personnel,1e,nominatif,neutre,singulier':'434',
'pronom-personnel,1e,nominatif,pluriel':'435',
'pronom-personnel,1e,nominatif,singulier':'436',
'pronom-personnel,2e,accusatif,masculin,pluriel':'437',
'pronom-personnel,2e,accusatif,masculin,singulier':'438',
'pronom-personnel,2e,accusatif,neutre,pluriel':'439',
'pronom-personnel,2e,accusatif,neutre,singulier':'440',
'pronom-personnel,2e,accusatif,pluriel':'441',
'pronom-personnel,2e,accusatif,singulier':'442',
'pronom-personnel,2e,datif,masculin,singulier':'443',
'pronom-personnel,2e,datif,pluriel':'444',
'pronom-personnel,2e,datif,singulier':'445',
'pronom-personnel,2e,génitif,féminin,singulier':'446',
'pronom-personnel,2e,génitif,pluriel':'447',
'pronom-personnel,2e,génitif,singulier':'448',
'pronom-personnel,2e,nominatif,féminin,pluriel':'449',
'pronom-personnel,2e,nominatif,masculin,pluriel':'450',
'pronom-personnel,2e,nominatif,neutre,pluriel':'451',
'pronom-personnel,2e,nominatif,neutre,singulier':'452',
'pronom-personnel,2e,nominatif,pluriel':'453',
'pronom-personnel,2e,nominatif,singulier':'454',
'pronom-personnel,2e,vocatif,masculin,pluriel':'455',
'pronom-personnel,3e,accusatif,féminin,pluriel':'456',
'pronom-personnel,3e,accusatif,féminin,singulier':'457',
'pronom-personnel,3e,accusatif,masculin,pluriel':'458',
'pronom-personnel,3e,accusatif,masculin,singulier':'459',
'pronom-personnel,3e,accusatif,neutre,pluriel':'460',
'pronom-personnel,3e,accusatif,neutre,singulier':'461',
'pronom-personnel,3e,datif,féminin,pluriel':'462',
'pronom-personnel,3e,datif,féminin,singulier':'463',
'pronom-personnel,3e,datif,masculin,pluriel':'464',
'pronom-personnel,3e,datif,masculin,singulier':'465',
'pronom-personnel,3e,datif,neutre,pluriel':'466',
'pronom-personnel,3e,datif,neutre,singulier':'467',
'pronom-personnel,3e,génitif,féminin,pluriel':'468',
'pronom-personnel,3e,génitif,féminin,singulier':'469',
'pronom-personnel,3e,génitif,masculin,pluriel':'470',
'pronom-personnel,3e,génitif,masculin,singulier':'471',
'pronom-personnel,3e,génitif,neutre,pluriel':'472',
'pronom-personnel,3e,génitif,neutre,singulier':'473',
'pronom-personnel,3e,nominatif,féminin,singulier':'474',
'pronom-personnel,3e,nominatif,masculin,pluriel':'475',
'pronom-personnel,3e,nominatif,masculin,singulier':'476',
'pronom-personnel,accusatif,masculin,pluriel':'477',
'pronom-personnel,accusatif,masculin,singulier':'478',
'pronom-personnel,datif,masculin,pluriel':'479',
'pronom-personnel,génitif,féminin,singulier':'480',
'pronom-personnel,génitif,masculin,pluriel':'481',
'pronom-personnel,génitif,masculin,singulier':'482',
'pronom-personnel,génitif,singulier':'483',
'pronom-relatif,accusatif,féminin,pluriel':'484',
'pronom-relatif,accusatif,féminin,singulier':'485',
'pronom-relatif,accusatif,masculin,pluriel':'486',
'pronom-relatif,accusatif,masculin,singulier':'487',
'pronom-relatif,accusatif,neutre,pluriel':'488',
'pronom-relatif,accusatif,neutre,singulier':'489',
'pronom-relatif,datif,féminin,pluriel':'490',
'pronom-relatif,datif,féminin,singulier':'491',
'pronom-relatif,datif,masculin,pluriel':'492',
'pronom-relatif,datif,masculin,singulier':'493',
'pronom-relatif,datif,neutre,pluriel':'494',
'pronom-relatif,datif,neutre,singulier':'495',
'pronom-relatif,génitif,féminin,pluriel':'496',
'pronom-relatif,génitif,féminin,singulier':'497',
'pronom-relatif,génitif,masculin,pluriel':'498',
'pronom-relatif,génitif,masculin,singulier':'499',
'pronom-relatif,génitif,neutre,pluriel':'500',
'pronom-relatif,génitif,neutre,singulier':'501',
'pronom-relatif,nominatif,féminin,pluriel':'502',
'pronom-relatif,nominatif,féminin,singulier':'503',
'pronom-relatif,nominatif,masculin,pluriel':'504',
'pronom-relatif,nominatif,masculin,singulier':'505',
'pronom-relatif,nominatif,neutre,pluriel':'506',
'pronom-relatif,nominatif,neutre,singulier':'507',
'pronom-réciproque,accusatif,masculin,pluriel':'508',
'pronom-réciproque,datif,masculin,pluriel':'509',
'pronom-réciproque,datif,neutre,pluriel':'510',
'pronom-réciproque,génitif,masculin,pluriel':'511',
'pronom-réciproque,génitif,neutre,pluriel':'512',
'pronom-réfléchi,1e,accusatif,masculin,pluriel':'513',
'pronom-réfléchi,1e,accusatif,masculin,singulier':'514',
'pronom-réfléchi,1e,datif,masculin,pluriel':'515',
'pronom-réfléchi,1e,datif,masculin,singulier':'516',
'pronom-réfléchi,1e,génitif,masculin,pluriel':'517',
'pronom-réfléchi,1e,génitif,masculin,singulier':'518',
'pronom-réfléchi,1e,nominatif,masculin,pluriel':'519',
'pronom-réfléchi,1e,nominatif,masculin,singulier':'520',
'pronom-réfléchi,2e,accusatif,féminin,pluriel':'521',
'pronom-réfléchi,2e,accusatif,masculin,pluriel':'522',
'pronom-réfléchi,2e,accusatif,masculin,singulier':'523',
'pronom-réfléchi,2e,accusatif,neutre,pluriel':'524',
'pronom-réfléchi,2e,datif,féminin,pluriel':'525',
'pronom-réfléchi,2e,datif,masculin,pluriel':'526',
'pronom-réfléchi,2e,datif,masculin,singulier':'527',
'pronom-réfléchi,2e,génitif,masculin,pluriel':'528',
'pronom-réfléchi,2e,génitif,masculin,singulier':'529',
'pronom-réfléchi,2e,nominatif,masculin,pluriel':'530',
'pronom-réfléchi,2e,nominatif,masculin,singulier':'531',
'pronom-réfléchi,3e,accusatif,féminin,pluriel':'532',
'pronom-réfléchi,3e,accusatif,féminin,singulier':'533',
'pronom-réfléchi,3e,accusatif,masculin,pluriel':'534',
'pronom-réfléchi,3e,accusatif,masculin,singulier':'535',
'pronom-réfléchi,3e,accusatif,neutre,pluriel':'536',
'pronom-réfléchi,3e,accusatif,neutre,singulier':'537',
'pronom-réfléchi,3e,datif,féminin,singulier':'538',
'pronom-réfléchi,3e,datif,masculin,pluriel':'539',
'pronom-réfléchi,3e,datif,masculin,singulier':'540',
'pronom-réfléchi,3e,génitif,féminin,pluriel':'541',
'pronom-réfléchi,3e,génitif,féminin,singulier':'542',
'pronom-réfléchi,3e,génitif,masculin,pluriel':'543',
'pronom-réfléchi,3e,génitif,masculin,singulier':'544',
'pronom-réfléchi,3e,génitif,neutre,pluriel':'545',
'pronom-réfléchi,3e,génitif,neutre,singulier':'546',
'pronom-réfléchi,3e,nominatif,féminin,singulier':'547',
'pronom-réfléchi,3e,nominatif,masculin,pluriel':'548',
'pronom-réfléchi,3e,nominatif,masculin,singulier':'549',
'pronom-réfléchi,3e,nominatif,neutre,singulier':'550',
'pronom-réfléchi,accusatif,féminin,singulier':'551',
'pronom-réfléchi,accusatif,neutre,singulier':'552',
'pronom-réfléchi,nominatif,masculin,singulier':'553',
'préposition':'554',
'préposition,accusatif':'555',
'préposition,datif':'556',
'préposition,génitif':'557',
'préposition-impropre':'558',
'préposition-impropre,datif':'559',
'préposition-impropre,génitif':'560',
'verbe,impératif,aoriste,actif,2e,pluriel':'561',
'verbe,impératif,aoriste,actif,2e,singulier':'562',
'verbe,impératif,aoriste,actif,3e,pluriel':'563',
'verbe,impératif,aoriste,actif,3e,singulier':'564',
'verbe,impératif,aoriste,moyen,2e,pluriel':'565',
'verbe,impératif,aoriste,moyen,2e,singulier':'566',
'verbe,impératif,aoriste,moyen,3e,pluriel':'567',
'verbe,impératif,aoriste,moyen,3e,singulier':'568',
'verbe,impératif,aoriste,moyen-passif,2e,singulier':'569',
'verbe,impératif,aoriste,passif,2e,pluriel':'570',
'verbe,impératif,aoriste,passif,2e,singulier':'571',
'verbe,impératif,aoriste,passif,3e,pluriel':'572',
'verbe,impératif,aoriste,passif,3e,singulier':'573',
'verbe,impératif,parfait,actif,2e,pluriel':'574',
'verbe,impératif,parfait,passif,2e,pluriel':'575',
'verbe,impératif,parfait,passif,2e,singulier':'576',
'verbe,impératif,présent,actif,2e,pluriel':'577',
'verbe,impératif,présent,actif,2e,singulier':'578',
'verbe,impératif,présent,actif,3e,pluriel':'579',
'verbe,impératif,présent,actif,3e,singulier':'580',
'verbe,impératif,présent,moyen,2e,pluriel':'581',
'verbe,impératif,présent,moyen,2e,singulier':'582',
'verbe,impératif,présent,moyen,3e,pluriel':'583',
'verbe,impératif,présent,moyen,3e,singulier':'584',
'verbe,impératif,présent,passif,2e,pluriel':'585',
'verbe,impératif,présent,passif,2e,singulier':'586',
'verbe,impératif,présent,passif,3e,pluriel':'587',
'verbe,impératif,présent,passif,3e,singulier':'588',
'verbe,indicatif,aoriste,actif,1e,pluriel':'589',
'verbe,indicatif,aoriste,actif,1e,singulier':'590',
'verbe,indicatif,aoriste,actif,2e,pluriel':'591',
'verbe,indicatif,aoriste,actif,2e,singulier':'592',
'verbe,indicatif,aoriste,actif,3e,pluriel':'593',
'verbe,indicatif,aoriste,actif,3e,singulier':'594',
'verbe,indicatif,aoriste,moyen,1e,pluriel':'595',
'verbe,indicatif,aoriste,moyen,1e,singulier':'596',
'verbe,indicatif,aoriste,moyen,2e,pluriel':'597',
'verbe,indicatif,aoriste,moyen,2e,singulier':'598',
'verbe,indicatif,aoriste,moyen,3e,pluriel':'599',
'verbe,indicatif,aoriste,moyen,3e,singulier':'600',
'verbe,indicatif,aoriste,moyen-passif,3e,pluriel':'601',
'verbe,indicatif,aoriste,moyen-passif,3e,singulier':'602',
'verbe,indicatif,aoriste,passif,1e,pluriel':'603',
'verbe,indicatif,aoriste,passif,1e,singulier':'604',
'verbe,indicatif,aoriste,passif,2e,pluriel':'605',
'verbe,indicatif,aoriste,passif,2e,singulier':'606',
'verbe,indicatif,aoriste,passif,3e,pluriel':'607',
'verbe,indicatif,aoriste,passif,3e,singulier':'608',
'verbe,indicatif,futur,actif,1e,pluriel':'609',
'verbe,indicatif,futur,actif,1e,singulier':'610',
'verbe,indicatif,futur,actif,2e,pluriel':'611',
'verbe,indicatif,futur,actif,2e,singulier':'612',
'verbe,indicatif,futur,actif,3e,pluriel':'613',
'verbe,indicatif,futur,actif,3e,singulier':'614',
'verbe,indicatif,futur,moyen,1e,pluriel':'615',
'verbe,indicatif,futur,moyen,1e,singulier':'616',
'verbe,indicatif,futur,moyen,2e,pluriel':'617',
'verbe,indicatif,futur,moyen,2e,singulier':'618',
'verbe,indicatif,futur,moyen,3e,pluriel':'619',
'verbe,indicatif,futur,moyen,3e,singulier':'620',
'verbe,indicatif,futur,moyen-passif,3e,singulier':'621',
'verbe,indicatif,futur,passif,1e,pluriel':'622',
'verbe,indicatif,futur,passif,1e,singulier':'623',
'verbe,indicatif,futur,passif,2e,pluriel':'624',
'verbe,indicatif,futur,passif,2e,singulier':'625',
'verbe,indicatif,futur,passif,3e,pluriel':'626',
'verbe,indicatif,futur,passif,3e,singulier':'627',
'verbe,indicatif,imparfait,actif,1e,pluriel':'628',
'verbe,indicatif,imparfait,actif,1e,singulier':'629',
'verbe,indicatif,imparfait,actif,2e,pluriel':'630',
'verbe,indicatif,imparfait,actif,2e,singulier':'631',
'verbe,indicatif,imparfait,actif,3e,pluriel':'632',
'verbe,indicatif,imparfait,actif,3e,singulier':'633',
'verbe,indicatif,imparfait,moyen,1e,pluriel':'634',
'verbe,indicatif,imparfait,moyen,1e,singulier':'635',
'verbe,indicatif,imparfait,moyen,2e,pluriel':'636',
'verbe,indicatif,imparfait,moyen,2e,singulier':'637',
'verbe,indicatif,imparfait,moyen,3e,pluriel':'638',
'verbe,indicatif,imparfait,moyen,3e,singulier':'639',
'verbe,indicatif,imparfait,passif,1e,pluriel':'640',
'verbe,indicatif,imparfait,passif,1e,singulier':'641',
'verbe,indicatif,imparfait,passif,2e,pluriel':'642',
'verbe,indicatif,imparfait,passif,3e,pluriel':'643',
'verbe,indicatif,imparfait,passif,3e,singulier':'644',
'verbe,indicatif,parfait,actif,1e,pluriel':'645',
'verbe,indicatif,parfait,actif,1e,singulier':'646',
'verbe,indicatif,parfait,actif,2e,pluriel':'647',
'verbe,indicatif,parfait,actif,2e,singulier':'648',
'verbe,indicatif,parfait,actif,3e,pluriel':'649',
'verbe,indicatif,parfait,actif,3e,singulier':'650',
'verbe,indicatif,parfait,moyen,1e,pluriel':'651',
'verbe,indicatif,parfait,moyen,1e,singulier':'652',
'verbe,indicatif,parfait,moyen,2e,pluriel':'653',
'verbe,indicatif,parfait,moyen,2e,singulier':'654',
'verbe,indicatif,parfait,moyen,3e,pluriel':'655',
'verbe,indicatif,parfait,moyen,3e,singulier':'656',
'verbe,indicatif,parfait,passif,1e,pluriel':'657',
'verbe,indicatif,parfait,passif,1e,singulier':'658',
'verbe,indicatif,parfait,passif,2e,pluriel':'659',
'verbe,indicatif,parfait,passif,2e,singulier':'660',
'verbe,indicatif,parfait,passif,3e,pluriel':'661',
'verbe,indicatif,parfait,passif,3e,singulier':'662',
'verbe,indicatif,plus-que-parfait,actif,1e,singulier':'663',
'verbe,indicatif,plus-que-parfait,actif,2e,pluriel':'664',
'verbe,indicatif,plus-que-parfait,actif,2e,singulier':'665',
'verbe,indicatif,plus-que-parfait,actif,3e,pluriel':'666',
'verbe,indicatif,plus-que-parfait,actif,3e,singulier':'667',
'verbe,indicatif,plus-que-parfait,moyen,3e,pluriel':'668',
'verbe,indicatif,plus-que-parfait,moyen,3e,singulier':'669',
'verbe,indicatif,plus-que-parfait,passif,3e,singulier':'670',
'verbe,indicatif,présent,actif,1e,pluriel':'671',
'verbe,indicatif,présent,actif,1e,singulier':'672',
'verbe,indicatif,présent,actif,2e,pluriel':'673',
'verbe,indicatif,présent,actif,2e,singulier':'674',
'verbe,indicatif,présent,actif,3e,pluriel':'675',
'verbe,indicatif,présent,actif,3e,singulier':'676',
'verbe,indicatif,présent,moyen,1e,pluriel':'677',
'verbe,indicatif,présent,moyen,1e,singulier':'678',
'verbe,indicatif,présent,moyen,2e,pluriel':'679',
'verbe,indicatif,présent,moyen,2e,singulier':'680',
'verbe,indicatif,présent,moyen,3e,pluriel':'681',
'verbe,indicatif,présent,moyen,3e,singulier':'682',
'verbe,indicatif,présent,passif,1e,pluriel':'683',
'verbe,indicatif,présent,passif,1e,singulier':'684',
'verbe,indicatif,présent,passif,2e,pluriel':'685',
'verbe,indicatif,présent,passif,2e,singulier':'686',
'verbe,indicatif,présent,passif,3e,pluriel':'687',
'verbe,indicatif,présent,passif,3e,singulier':'688',
'verbe,infinitif,aoriste,actif':'689',
'verbe,infinitif,aoriste,actif,':'690',
'verbe,infinitif,aoriste,moyen':'691',
'verbe,infinitif,aoriste,passif':'692',
'verbe,infinitif,futur,actif':'693',
'verbe,infinitif,futur,moyen':'694',
'verbe,infinitif,parfait,actif':'695',
'verbe,infinitif,parfait,moyen':'696',
'verbe,infinitif,parfait,passif':'697',
'verbe,infinitif,présent,actif':'698',
'verbe,infinitif,présent,moyen':'699',
'verbe,infinitif,présent,moyen-passif':'700',
'verbe,infinitif,présent,passif':'701',
'verbe,optatif,aoriste,actif,3e,pluriel':'702',
'verbe,optatif,aoriste,actif,3e,singulier':'703',
'verbe,optatif,aoriste,moyen,1e,singulier':'704',
'verbe,optatif,aoriste,moyen,3e,singulier':'705',
'verbe,optatif,aoriste,passif,3e,singulier':'706',
'verbe,optatif,présent,actif,2e,pluriel':'707',
'verbe,optatif,présent,actif,3e,pluriel':'708',
'verbe,optatif,présent,actif,3e,singulier':'709',
'verbe,optatif,présent,moyen,1e,singulier':'710',
'verbe,optatif,présent,moyen,3e,pluriel':'711',
'verbe,optatif,présent,moyen,3e,singulier':'712',
'verbe,participe,aoriste,actif,accusatif,féminin,pluriel':'713',
'verbe,participe,aoriste,actif,accusatif,féminin,singulier':'714',
'verbe,participe,aoriste,actif,accusatif,masculin,pluriel':'715',
'verbe,participe,aoriste,actif,accusatif,masculin,singulier':'716',
'verbe,participe,aoriste,actif,accusatif,neutre,pluriel':'717',
'verbe,participe,aoriste,actif,accusatif,neutre,singulier':'718',
'verbe,participe,aoriste,actif,datif,féminin,pluriel':'719',
'verbe,participe,aoriste,actif,datif,féminin,singulier':'720',
'verbe,participe,aoriste,actif,datif,masculin,pluriel':'721',
'verbe,participe,aoriste,actif,datif,masculin,singulier':'722',
'verbe,participe,aoriste,actif,génitif,féminin,singulier':'723',
'verbe,participe,aoriste,actif,génitif,masculin,pluriel':'724',
'verbe,participe,aoriste,actif,génitif,masculin,singulier':'725',
'verbe,participe,aoriste,actif,génitif,neutre,singulier':'726',
'verbe,participe,aoriste,actif,nominatif,féminin,pluriel':'727',
'verbe,participe,aoriste,actif,nominatif,féminin,singulier':'728',
'verbe,participe,aoriste,actif,nominatif,masculin,pluriel':'729',
'verbe,participe,aoriste,actif,nominatif,masculin,singulier':'730',
'verbe,participe,aoriste,actif,nominatif,neutre,pluriel':'731',
'verbe,participe,aoriste,actif,nominatif,neutre,singulier':'732',
'verbe,participe,aoriste,moyen,accusatif,féminin,singulier':'733',
'verbe,participe,aoriste,moyen,accusatif,masculin,pluriel':'734',
'verbe,participe,aoriste,moyen,accusatif,masculin,singulier':'735',
'verbe,participe,aoriste,moyen,accusatif,neutre,pluriel':'736',
'verbe,participe,aoriste,moyen,accusatif,neutre,singulier':'737',
'verbe,participe,aoriste,moyen,datif,masculin,pluriel':'738',
'verbe,participe,aoriste,moyen,datif,neutre,pluriel':'739',
'verbe,participe,aoriste,moyen,génitif,féminin,pluriel':'740',
'verbe,participe,aoriste,moyen,génitif,féminin,singulier':'741',
'verbe,participe,aoriste,moyen,génitif,masculin,pluriel':'742',
'verbe,participe,aoriste,moyen,génitif,masculin,singulier':'743',
'verbe,participe,aoriste,moyen,génitif,neutre,pluriel':'744',
'verbe,participe,aoriste,moyen,génitif,neutre,singulier':'745',
'verbe,participe,aoriste,moyen,nominatif,féminin,pluriel':'746',
'verbe,participe,aoriste,moyen,nominatif,féminin,singulier':'747',
'verbe,participe,aoriste,moyen,nominatif,masculin,pluriel':'748',
'verbe,participe,aoriste,moyen,nominatif,masculin,singulier':'749',
'verbe,participe,aoriste,moyen,nominatif,neutre,singulier':'750',
'verbe,participe,aoriste,passif,accusatif,féminin,singulier':'751',
'verbe,participe,aoriste,passif,accusatif,masculin,pluriel':'752',
'verbe,participe,aoriste,passif,accusatif,masculin,singulier':'753',
'verbe,participe,aoriste,passif,accusatif,neutre,pluriel':'754',
'verbe,participe,aoriste,passif,accusatif,neutre,singulier':'755',
'verbe,participe,aoriste,passif,datif,féminin,singulier':'756',
'verbe,participe,aoriste,passif,datif,masculin,singulier':'757',
'verbe,participe,aoriste,passif,datif,neutre,pluriel':'758',
'verbe,participe,aoriste,passif,datif,neutre,singulier':'759',
'verbe,participe,aoriste,passif,génitif,féminin,pluriel':'760',
'verbe,participe,aoriste,passif,génitif,féminin,singulier':'761',
'verbe,participe,aoriste,passif,génitif,masculin,pluriel':'762',
'verbe,participe,aoriste,passif,génitif,masculin,singulier':'763',
'verbe,participe,aoriste,passif,génitif,neutre,pluriel':'764',
'verbe,participe,aoriste,passif,génitif,neutre,singulier':'765',
'verbe,participe,aoriste,passif,nominatif,féminin,pluriel':'766',
'verbe,participe,aoriste,passif,nominatif,féminin,singulier':'767',
'verbe,participe,aoriste,passif,nominatif,masculin,pluriel':'768',
'verbe,participe,aoriste,passif,nominatif,masculin,singulier':'769',
'verbe,participe,aoriste,passif,nominatif,neutre,pluriel':'770',
'verbe,participe,aoriste,passif,nominatif,neutre,singulier':'771',
'verbe,participe,futur,actif,accusatif,neutre,pluriel':'772',
'verbe,participe,futur,actif,nominatif,masculin,pluriel':'773',
'verbe,participe,futur,actif,nominatif,masculin,singulier':'774',
'verbe,participe,futur,moyen,accusatif,neutre,singulier':'775',
'verbe,participe,futur,passif,génitif,neutre,pluriel':'776',
'verbe,participe,parfait,actif,accusatif,féminin,singulier':'777',
'verbe,participe,parfait,actif,accusatif,masculin,pluriel':'778',
'verbe,participe,parfait,actif,accusatif,masculin,singulier':'779',
'verbe,participe,parfait,actif,accusatif,neutre,pluriel':'780',
'verbe,participe,parfait,actif,accusatif,neutre,singulier':'781',
'verbe,participe,parfait,actif,datif,masculin,pluriel':'782',
'verbe,participe,parfait,actif,datif,masculin,singulier':'783',
'verbe,participe,parfait,actif,datif,neutre,singulier':'784',
'verbe,participe,parfait,actif,génitif,féminin,singulier':'785',
'verbe,participe,parfait,actif,génitif,masculin,pluriel':'786',
'verbe,participe,parfait,actif,génitif,masculin,singulier':'787',
'verbe,participe,parfait,actif,génitif,neutre,pluriel':'788',
'verbe,participe,parfait,actif,nominatif,féminin,pluriel':'789',
'verbe,participe,parfait,actif,nominatif,féminin,singulier':'790',
'verbe,participe,parfait,actif,nominatif,masculin,pluriel':'791',
'verbe,participe,parfait,actif,nominatif,masculin,singulier':'792',
'verbe,participe,parfait,actif,nominatif,neutre,pluriel':'793',
'verbe,participe,parfait,actif,nominatif,neutre,singulier':'794',
'verbe,participe,parfait,moyen,accusatif,féminin,singulier':'795',
'verbe,participe,parfait,moyen,accusatif,masculin,pluriel':'796',
'verbe,participe,parfait,moyen,accusatif,masculin,singulier':'797',
'verbe,participe,parfait,moyen,datif,féminin,pluriel':'798',
'verbe,participe,parfait,moyen,génitif,féminin,singulier':'799',
'verbe,participe,parfait,moyen,nominatif,masculin,pluriel':'800',
'verbe,participe,parfait,moyen,nominatif,masculin,singulier':'801',
'verbe,participe,parfait,passif,accusatif,féminin,pluriel':'802',
'verbe,participe,parfait,passif,accusatif,féminin,singulier':'803',
'verbe,participe,parfait,passif,accusatif,masculin,pluriel':'804',
'verbe,participe,parfait,passif,accusatif,masculin,singulier':'805',
'verbe,participe,parfait,passif,accusatif,neutre,pluriel':'806',
'verbe,participe,parfait,passif,accusatif,neutre,singulier':'807',
'verbe,participe,parfait,passif,datif,féminin,singulier':'808',
'verbe,participe,parfait,passif,datif,masculin,pluriel':'809',
'verbe,participe,parfait,passif,datif,masculin,singulier':'810',
'verbe,participe,parfait,passif,datif,neutre,pluriel':'811',
'verbe,participe,parfait,passif,datif,neutre,singulier':'812',
'verbe,participe,parfait,passif,génitif,féminin,pluriel':'813',
'verbe,participe,parfait,passif,génitif,féminin,singulier':'814',
'verbe,participe,parfait,passif,génitif,masculin,pluriel':'815',
'verbe,participe,parfait,passif,génitif,masculin,singulier':'816',
'verbe,participe,parfait,passif,génitif,neutre,pluriel':'817',
'verbe,participe,parfait,passif,génitif,neutre,singulier':'818',
'verbe,participe,parfait,passif,nominatif,féminin,pluriel':'819',
'verbe,participe,parfait,passif,nominatif,féminin,singulier':'820',
'verbe,participe,parfait,passif,nominatif,masculin,pluriel':'821',
'verbe,participe,parfait,passif,nominatif,masculin,singulier':'822',
'verbe,participe,parfait,passif,nominatif,neutre,pluriel':'823',
'verbe,participe,parfait,passif,nominatif,neutre,singulier':'824',
'verbe,participe,parfait,passif,vocatif,féminin,singulier':'825',
'verbe,participe,parfait,passif,vocatif,masculin,pluriel':'826',
'verbe,participe,parfait,passif,vocatif,masculin,singulier':'827',
'verbe,participe,présent,actif,accusatif,féminin,pluriel':'828',
'verbe,participe,présent,actif,accusatif,féminin,singulier':'829',
'verbe,participe,présent,actif,accusatif,masculin,pluriel':'830',
'verbe,participe,présent,actif,accusatif,masculin,singulier':'831',
'verbe,participe,présent,actif,accusatif,neutre,pluriel':'832',
'verbe,participe,présent,actif,accusatif,neutre,singulier':'833',
'verbe,participe,présent,actif,datif,féminin,pluriel':'834',
'verbe,participe,présent,actif,datif,féminin,singulier':'835',
'verbe,participe,présent,actif,datif,masculin,pluriel':'836',
'verbe,participe,présent,actif,datif,masculin,singulier':'837',
'verbe,participe,présent,actif,datif,neutre,pluriel':'838',
'verbe,participe,présent,actif,datif,neutre,singulier':'839',
'verbe,participe,présent,actif,génitif,féminin,pluriel':'840',
'verbe,participe,présent,actif,génitif,féminin,singulier':'841',
'verbe,participe,présent,actif,génitif,masculin,pluriel':'842',
'verbe,participe,présent,actif,génitif,masculin,singulier':'843',
'verbe,participe,présent,actif,génitif,neutre,pluriel':'844',
'verbe,participe,présent,actif,génitif,neutre,singulier':'845',
'verbe,participe,présent,actif,nominatif,féminin,pluriel':'846',
'verbe,participe,présent,actif,nominatif,féminin,singulier':'847',
'verbe,participe,présent,actif,nominatif,masculin,pluriel':'848',
'verbe,participe,présent,actif,nominatif,masculin,singulier':'849',
'verbe,participe,présent,actif,nominatif,neutre,pluriel':'850',
'verbe,participe,présent,actif,nominatif,neutre,singulier':'851',
'verbe,participe,présent,actif,vocatif,féminin,singulier':'852',
'verbe,participe,présent,actif,vocatif,masculin,pluriel':'853',
'verbe,participe,présent,actif,vocatif,masculin,singulier':'854',
'verbe,participe,présent,moyen,accusatif,féminin,pluriel':'855',
'verbe,participe,présent,moyen,accusatif,féminin,singulier':'856',
'verbe,participe,présent,moyen,accusatif,masculin,pluriel':'857',
'verbe,participe,présent,moyen,accusatif,masculin,singulier':'858',
'verbe,participe,présent,moyen,accusatif,neutre,pluriel':'859',
'verbe,participe,présent,moyen,accusatif,neutre,singulier':'860',
'verbe,participe,présent,moyen,datif,féminin,pluriel':'861',
'verbe,participe,présent,moyen,datif,féminin,singulier':'862',
'verbe,participe,présent,moyen,datif,masculin,pluriel':'863',
'verbe,participe,présent,moyen,datif,masculin,singulier':'864',
'verbe,participe,présent,moyen,datif,neutre,pluriel':'865',
'verbe,participe,présent,moyen,datif,neutre,singulier':'866',
'verbe,participe,présent,moyen,génitif,féminin,pluriel':'867',
'verbe,participe,présent,moyen,génitif,féminin,singulier':'868',
'verbe,participe,présent,moyen,génitif,masculin,pluriel':'869',
'verbe,participe,présent,moyen,génitif,masculin,singulier':'870',
'verbe,participe,présent,moyen,génitif,neutre,pluriel':'871',
'verbe,participe,présent,moyen,génitif,neutre,singulier':'872',
'verbe,participe,présent,moyen,nominatif,féminin,pluriel':'873',
'verbe,participe,présent,moyen,nominatif,féminin,singulier':'874',
'verbe,participe,présent,moyen,nominatif,masculin,pluriel':'875',
'verbe,participe,présent,moyen,nominatif,masculin,singulier':'876',
'verbe,participe,présent,moyen,nominatif,neutre,pluriel':'877',
'verbe,participe,présent,moyen,nominatif,neutre,singulier':'878',
'verbe,participe,présent,moyen,vocatif,masculin,pluriel':'879',
'verbe,participe,présent,moyen,vocatif,masculin,singulier':'880',
'verbe,participe,présent,passif,accusatif,féminin,pluriel':'881',
'verbe,participe,présent,passif,accusatif,féminin,singulier':'882',
'verbe,participe,présent,passif,accusatif,masculin,pluriel':'883',
'verbe,participe,présent,passif,accusatif,masculin,singulier':'884',
'verbe,participe,présent,passif,accusatif,neutre,pluriel':'885',
'verbe,participe,présent,passif,accusatif,neutre,singulier':'886',
'verbe,participe,présent,passif,datif,féminin,singulier':'887',
'verbe,participe,présent,passif,datif,masculin,pluriel':'888',
'verbe,participe,présent,passif,datif,masculin,singulier':'889',
'verbe,participe,présent,passif,datif,neutre,pluriel':'890',
'verbe,participe,présent,passif,datif,neutre,singulier':'891',
'verbe,participe,présent,passif,génitif,féminin,singulier':'892',
'verbe,participe,présent,passif,génitif,masculin,pluriel':'893',
'verbe,participe,présent,passif,génitif,masculin,singulier':'894',
'verbe,participe,présent,passif,génitif,neutre,pluriel':'895',
'verbe,participe,présent,passif,génitif,neutre,singulier':'896',
'verbe,participe,présent,passif,nominatif,féminin,pluriel':'897',
'verbe,participe,présent,passif,nominatif,féminin,singulier':'898',
'verbe,participe,présent,passif,nominatif,masculin,pluriel':'899',
'verbe,participe,présent,passif,nominatif,masculin,singulier':'900',
'verbe,participe,présent,passif,nominatif,neutre,pluriel':'901',
'verbe,participe,présent,passif,nominatif,neutre,singulier':'902',
'verbe,subjonctif,aoriste,actif,1e,pluriel':'903',
'verbe,subjonctif,aoriste,actif,1e,singulier':'904',
'verbe,subjonctif,aoriste,actif,2e,pluriel':'905',
'verbe,subjonctif,aoriste,actif,2e,singulier':'906',
'verbe,subjonctif,aoriste,actif,3e,pluriel':'907',
'verbe,subjonctif,aoriste,actif,3e,singulier':'908',
'verbe,subjonctif,aoriste,moyen,1e,pluriel':'909',
'verbe,subjonctif,aoriste,moyen,1e,singulier':'910',
'verbe,subjonctif,aoriste,moyen,2e,pluriel':'911',
'verbe,subjonctif,aoriste,moyen,2e,singulier':'912',
'verbe,subjonctif,aoriste,moyen,3e,pluriel':'913',
'verbe,subjonctif,aoriste,moyen,3e,singulier':'914',
'verbe,subjonctif,aoriste,passif,1e,pluriel':'915',
'verbe,subjonctif,aoriste,passif,1e,singulier':'916',
'verbe,subjonctif,aoriste,passif,2e,pluriel':'917',
'verbe,subjonctif,aoriste,passif,2e,singulier':'918',
'verbe,subjonctif,aoriste,passif,3e,pluriel':'919',
'verbe,subjonctif,aoriste,passif,3e,singulier':'920',
'verbe,subjonctif,parfait,actif,1e,pluriel':'921',
'verbe,subjonctif,parfait,actif,1e,singulier':'922',
'verbe,subjonctif,parfait,actif,2e,pluriel':'923',
'verbe,subjonctif,parfait,actif,2e,singulier':'924',
'verbe,subjonctif,présent,actif,1e,pluriel':'925',
'verbe,subjonctif,présent,actif,1e,singulier':'926',
'verbe,subjonctif,présent,actif,2e,pluriel':'927',
'verbe,subjonctif,présent,actif,2e,singulier':'928',
'verbe,subjonctif,présent,actif,3e,pluriel':'929',
'verbe,subjonctif,présent,actif,3e,singulier':'930',
'verbe,subjonctif,présent,moyen,1e,pluriel':'931',
'verbe,subjonctif,présent,moyen,1e,singulier':'932',
'verbe,subjonctif,présent,moyen,2e,pluriel':'933',
'verbe,subjonctif,présent,moyen,2e,singulier':'934',
'verbe,subjonctif,présent,moyen,3e,pluriel':'935',
'verbe,subjonctif,présent,moyen,3e,singulier':'936',
'verbe,subjonctif,présent,passif,1e,pluriel':'937',
'verbe,subjonctif,présent,passif,1e,singulier':'938',
'verbe,subjonctif,présent,passif,2e,pluriel':'939',
'verbe,subjonctif,présent,passif,3e,pluriel':'940',
'verbe,subjonctif,présent,passif,3e,singulier':'941',
'–':'942'
}



head_html = `<!DOCTYPE html>
<html lang="fr">

	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="Nouveau Testament">
		<meta name="keywords" content="Nouveau Testament">
	
		<title>NOUVEAU TESTAMENT</title>
`

css_web = `
		<style>
		
		html {
			margin:30px;
		}


		body {
			font-family: sans-serif;
			font-size:17px;
		}


		.chap {
			font-size:20px;
			float:left;
			margin:10px;
		}

		.ver {
			font-size:17px;
			font-weight:bold;
		}

		.text {
			font-size:17px;


		}

		</style>
	</head>
<body>
`;



css_papier = `
		<style>
		
		html {
			margin:0px;
		}


		body {
			margin:0px;
			font-family: Serif;
			font-size:11px;
		}


		.chap {
			font-size:14px;
		}

		.ver {
			font-size:11px;
			font-weight:bold;
		}

		.text {
			font-size:11px;
		}

		</style>
	</head>
<body>
`;






book = {
1:'MATTHIEU',
2:'MARC',
3:'LUC',
4:'JEAN',
5:'ACTES',
6:'ROMAINS',
7:'1 CORINTHIENS',
8:'2 CORINTHIENS',
9:'GALATES',
10:'EPHESIENS',
11:'PHILIPPIENS',
12:'COLOSSIENS',
13:'1 TESSALONICIENS',
14:'2 TESSALONICIENS',
15:'1 TIMOTHEE',
16:'2 TIMOTHEE',
17:'TITE',
18:'PHILEMON',
19:'HEBREUX',
20:'JACQUES',
21:'1 PIERRE',
22:'2 PIERRE',
23:'1 JEAN',
24:'2 JEAN',
25:'3 JEAN',
26:'JUDAS',
27:'APOCALYPSE'
}


biblos = {
1:'ΚΑΤΑ ΜΑΘΘΑΙΟΝ',
2:'ΚΑΤΑ ΜΑΡΚΟΝ',
3:'ΚΑΤΑ ΛΟΥΚΑΝ',
4:'ΚΑΤΑ ΙΩΑΝΝΗΝ',
5:'ΠΡΑΞΕΙΣ ΑΠΟΣΤΟΛΩΝ',
6:'ΠΡΟΣ ΡΩΜΑΙΟΥΣ',
7:'ΠΡΟΣ ΚΟΡΙΝΘΙΟΥΣ Α',
8:'ΠΡΟΣ ΚΟΡΙΝΘΙΟΥΣ Β',
9:'ΠΡΟΣ ΓΑΛΑΤΑΣ',
10:'ΠΡΟΣ ΕΦΕΣΙΟΥΣ',
11:'ΠΡΟΣ ΦΙΛΙΠΠΗΣΙΟΥΣ',
12:'ΠΡΟΣ ΚΟΛΟΣΣΑΕΙΣ',
13:'ΠΡΟΣ ΘΕΣΣΑΛΟΝΙΚΕΙΣ Α',
14:'ΠΡΟΣ ΘΕΣΣΑΛΟΝΙΚΕΙΣ Β',
15:'ΠΡΟΣ ΤΙΜΟΘΕΟΝ Α',
16:'ΠΡΟΣ ΤΙΜΟΘΕΟΝ Β',
17:'ΠΡΟΣ ΤΙΤΟΝ',
18:'ΠΡΟΣ ΦΙΛΗΜΟΝΑ',
19:'ΠΡΟΣ ΕΒΡΑΙΟΥΣ',
20:'ΙΑΚΩΒΟΥ',
21:'ΠΕΤΡΟΥ Α',
22:'ΠΕΤΡΟΥ Β',
23:'ΙΩΑΝΝΟΥ Α',
24:'ΙΩΑΝΝΟΥ Β',
25:'ΙΩΑΝΝΟΥ Γ',
26:'ΙΟΥΔΑ',
27:'ΑΠΟΚΑΛΥΨΙΣ ΙΩΑΝΝΟΥ'
}


function filtre(mo)
{
	mo=mo.normalize('NFD').replace(/[\u0300-\u036f]/g, "");
	mo=mo.toLowerCase();
	mo=mo.replace(/¶|⋄|\?|!|\(|\)|–|:|;|,|\.|\·|“|”|‘|’|᾽|ʼ|\*|\[|\]|…|\|/gi,'');

	return mo;
}



body_html_all	= '';
body_html		= '';
chapitreb		= 0;
livreb			= '';

fs			= require('fs');
file		= require('fs');
file2		= require('fs');
sebastien_te	= fs.readFileSync('../../database/sebastien_te.txt', 'utf8').split(/\r?\n/);
sebastien_fr	= fs.readFileSync('../../database/sebastien_fr.txt', 'utf8').split(/\r?\n/);


//check 1
if (sebastien_fr.length != sebastien_te.length)
	console.log('erreur 1')

for (nb=0;nb!=sebastien_te.length;nb++)
{
	
	//check 2
	if (sebastien_te[nb] != '' && sebastien_fr[nb] != '')
	{

/**

        V5      1:1:1:MATTHIEU:1:0:2021:SEBASTIEN-D-G Βίβλος=βίβλος=nom,nominatif,féminin,singulier γενέσεως=γένεσις=nom,génitif,féminin,singulier Ἰησοῦ=Ἰησοῦς=nom,génitif,masculin,singulier Χριστοῦ=Χριστός=nom,génitif,masculin,singulier υἱοῦ=υἱός=nom,génitif,masculin,singulier Δαυὶδ=Δαυίδ=nom,génitif,masculin,singulier υἱοῦ=υἱός=nom,génitif,masculin,singulier Ἀβραάμ.=Ἀβραάμ=nom,génitif,masculin,singulier
                0 1 2 3        4 5 6    7             		
**/

		te		= sebastien_te[nb].split(' ');
		fr		= sebastien_fr[nb].split(' ');
		
		lcvteinfo	= te[0].split(':');
		lcvfrinfo	= fr[0].split(':');
	
		lcvte = lcvteinfo[0]+':'+lcvteinfo[1]+':'+lcvteinfo[2]
		lcvfr = lcvfrinfo[0]+':'+lcvfrinfo[1]+':'+lcvfrinfo[2]
		
		//check 3
		if (lcvte != lcvfr)
			console.log(lcvte + ' '+ lcvfr)
		
		
		textete = sebastien_te[nb].replace(te[0]+' ', "").split(' ')
		textefr = sebastien_fr[nb].replace(fr[0]+' ', "").split('#')
		
		//check 4
		if (textete.length != textefr.length)
		{
			console.log(textete)
			console.log(textefr)
		}
		
		livre		= lcvteinfo[0];
		chapitre	= lcvteinfo[1];
		verset		= lcvteinfo[2];
		frnomlivre	= lcvteinfo[3];
		elnomlivre	= biblos[livre];
		
		nomdulivre = elnomlivre+' - '+frnomlivre
		
		
		//newtexte
		texte = ''
		for (x = 0 ; x != textete.length ; x++)
		{
			texte += textete[x].split('=')[0]+'<sup>'+morph[textete[x].split('=')[2]]+'</sup>'+textefr[x]+' ';
			
			//OPTION
			//.replace(/\.$/,'.&nbsp;&nbsp;');
			//.replace(/\·$/,'·&nbsp;&nbsp;');
			//.replace(/\;$/,';&nbsp;&nbsp;');
			
			
		}


		//console.log(texte)

		if (livreb != livre)
		{
			chapitreb	= 0;
			if (livreb != '')
				file2.appendFileSync(livreb+'.html','</body></html>', 'utf8');
				
			file2.writeFileSync(livre+'.html',head_html+css_web, 'utf8');
		}


		if (chapitre == 1 && verset == 1)
		{
			body_html_all	+= '\n<h3><center>'+nomdulivre+'</center></h3>\n';
			file2.appendFileSync(livre+'.html','\n<h3><center>'+nomdulivre+'</center></h3>\n', 'utf8');
		}


		if (chapitreb != chapitre)
		{
			body_html_all	+= '<br><br><div class="chap">'+nomdulivre+' &ensp;'+chapitre+'</div>\n';
			file2.appendFileSync(livre+'.html','<br><br><div class="chap">'+nomdulivre+' &ensp;'+chapitre+'</div>\n', 'utf8');
		}


		body_html_all	+= '<span class="ver"><b>'+verset+'</b></span> ';
		body_html_all	+= '<span class="text">'+texte+'</span>\n';

		body_html	+= '<span class="ver"><b>'+verset+'</b></span> ';
		body_html	+= '<span class="text">'+texte+'</span>\n';

		file2.appendFileSync(livre+'.html','<span class="ver"><b>'+verset+'</b></span> <span class="text">'+texte+'</span>\n', 'utf8');

		if (livre == 27 && chapitre == 22 && verset == 21)
			file2.appendFileSync(livreb+'.html','</body></html>', 'utf8');



		livreb		= livre;
		chapitreb	= chapitre;
		

		
		
	}


}

file.writeFileSync('all.html',head_html+css_papier+body_html_all+'</body></html>', 'utf8');

